/**
 * Talent DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Talent Domain Module - Composition root
 *
 * DDD: Composition root for talent domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  GapRepositoryAdapter,
} from "@morphora/adapters/talent";
import { getIdGeneratorService } from "@morphora/adapters";
import type { AdapterDynamoDBClient } from "@morphora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateTalentGap,
  ExecuteGetTalentGap,
  ExecuteListTalentGaps,
  ExecuteUpdateTalentGap,
} from "@morphora/services/talent/usecases";
// Ports (interfaces)
import type {
  GapRepository,
} from "@morphora/services/talent/ports";

export interface TalentDomainModule {
  repos: {
    gaps: GapRepository;
  };
  useCases: {
    gaps: {
      create: ExecuteCreateTalentGap;
      get: ExecuteGetTalentGap;
      list: ExecuteListTalentGaps;
      update: ExecuteUpdateTalentGap;
    };
  };
}

export function buildTalentDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TalentDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      gaps?: GapRepository;
    } = {};

    obj.gaps = new GapRepositoryAdapter(dynamoClient);
    return {
      gaps: obj.gaps!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    gaps: {
      create: new ExecuteCreateTalentGap(executionContext, idGenerator, repos.gaps),
      get: new ExecuteGetTalentGap(executionContext, idGenerator, repos.gaps),
      list: new ExecuteListTalentGaps(executionContext, idGenerator, repos.gaps),
      update: new ExecuteUpdateTalentGap(executionContext, idGenerator, repos.gaps),
    },
  };
  return { repos, useCases: useCases as TalentDomainModule["useCases"] };
}
