/**
 * Handlers for Criticality
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PartnersDomainModule } from "../dependencies/partners-ddd.dependencies.js";
import type { SetPartnerCriticalityInput } from "@morphora/services/partners";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v0/tenants/me/partners/{partnerId}/criticality
 * Operation: setPartnerCriticality
 */
export async function setPartnerCriticality(
  request: FastifyRequest<{ Params: { partnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PartnersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const body = (request.body ?? {}) as Record<string, unknown>;
  const input = { ...body, partnerId: request.params.partnerId } as SetPartnerCriticalityInput;
  const result = await deps.useCases.criticalities.update.execute(input);
  return reply.code(200).send(result);
}


