/**
 * Routes for Disposition
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { setCoreSystemDisposition } from "../handlers/disposition.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dispositionRoutes(fastify: FastifyInstance) {
  // PUT /v0/tenants/me/footprint/systems/{systemId}/disposition (unscoped; scope set for security middleware)
  fastify.put(
    "/v0/tenants/me/footprint/systems/:systemId/disposition",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { systemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFootprintDependenciesForRequest();
        await setCoreSystemDisposition(request, reply, deps);
      });
    }
  );


}
