/**
 * Routes for System
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createCoreSystem, getCoreSystem, listCoreSystems } from "../handlers/system.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function systemRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/footprint/systems (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/footprint/systems",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFootprintDependenciesForRequest();
        await createCoreSystem(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/footprint/systems (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/footprint/systems",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFootprintDependenciesForRequest();
        await listCoreSystems(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/footprint/systems/{systemId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/footprint/systems/:systemId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { systemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFootprintDependenciesForRequest();
        await getCoreSystem(request, reply, deps);
      });
    }
  );


}
