/**
 * ExecuteUpdateTalentGap - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateTalentGap Use Case
 *
 * DDD: Application use case for update Gap.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateTalentGapInput, UpdateTalentGapOutput } from "../dto/gap.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { GapRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateTalentGap {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly gap: GapRepository
  ) {}

  async execute(input: UpdateTalentGapInput): Promise<UpdateTalentGapOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tlnId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).gapId) {
      throw new ValidationError("gapId is required");
    }
    const gapId = (input as any).gapId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.gap.updateTalentGap({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateTalentGapOutput;
  }
}
