/**
 * GetSensingSignal handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSensingSignal } from "@morphora/api-server/domains/sensing/handlers";
import type { SensingDDDDependencies } from "@morphora/api-server/domains/sensing";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@morphora/tests/shared";
import { SENSING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSensingSignal", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SensingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SensingDDDDependencies>(
      SENSING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSensingSignal, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { signalId: entity.id };

    await getSensingSignal(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSensingSignal.execute).toHaveBeenCalledWith(expect.objectContaining({ signalId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { signalId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSensingSignal, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSensingSignal(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
