/**
 * ExecuteGetShadowITCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetShadowITCase Use Case
 *
 * DDD: Application use case for get ShadowIt.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetShadowITCaseInput, GetShadowITCaseOutput } from "../dto/shadow-it.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { ShadowItRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetShadowITCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly shadowIt: ShadowItRepository
  ) {}

  async execute(input: GetShadowITCaseInput): Promise<GetShadowITCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cseId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).caseId) {
      throw new ValidationError("caseId is required");
    }
    const caseId = (input as any).caseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.shadowIt.getShadowITCase({ caseId: caseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${caseId}`);
    }

    return entity as GetShadowITCaseOutput;
  }
}
