/**
 * CreateChallengerInitiative handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createChallengerInitiative } from "@morphora/api-server/domains/initiatives/handlers";
import type { InitiativesDDDDependencies } from "@morphora/api-server/domains/initiatives";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@morphora/tests/shared";
import { INITIATIVES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateChallengerInitiative", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InitiativesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InitiativesDDDDependencies>(
      INITIATIVES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateChallengerInitiative, "execute").mockResolvedValue(useCaseResult);

    await createChallengerInitiative(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateChallengerInitiative.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
