/**
 * GetChallengerInitiative handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getChallengerInitiative } from "@morphora/api-server/domains/initiatives/handlers";
import type { InitiativesDDDDependencies } from "@morphora/api-server/domains/initiatives";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@morphora/tests/shared";
import { INITIATIVES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetChallengerInitiative", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InitiativesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InitiativesDDDDependencies>(
      INITIATIVES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetChallengerInitiative, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { initiativeId: entity.id };

    await getChallengerInitiative(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetChallengerInitiative.execute).toHaveBeenCalledWith(expect.objectContaining({ initiativeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { initiativeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetChallengerInitiative, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getChallengerInitiative(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
