/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./initiative-repository.ddb.js";
export * from "./kill-repository.ddb.js";
export * from "./scale-repository.ddb.js";
export * from "./sourcing-repository.ddb.js";
export * from "./initiative-repository.adapter.js";
export * from "./kill-repository.adapter.js";
export * from "./scale-repository.adapter.js";
export * from "./sourcing-repository.adapter.js";
