/**
 * InitiativeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InitiativeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InitiativeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InitiativeRepository,
} from "@morphora/services/initiatives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InitiativeRepositoryDdb } from "./initiative-repository.ddb.js";

/**
 * InitiativeRepositoryAdapter
 *
 * Implements InitiativeRepository port for infrastructure layer.
 */
export class InitiativeRepositoryAdapter implements InitiativeRepository {
  private readonly ddb: InitiativeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InitiativeRepositoryDdb(this.dynamoClient);
  }

  async listChallengerInitiatives(input: Parameters<InitiativeRepository['listChallengerInitiatives']>[0]): Promise<Awaited<ReturnType<InitiativeRepository['listChallengerInitiatives']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listChallengerInitiatives(input);
  }

  async createChallengerInitiative(input: Parameters<InitiativeRepository['createChallengerInitiative']>[0]): Promise<Awaited<ReturnType<InitiativeRepository['createChallengerInitiative']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createChallengerInitiative(input);
  }

  async getChallengerInitiative(input: Parameters<InitiativeRepository['getChallengerInitiative']>[0]): Promise<Awaited<ReturnType<InitiativeRepository['getChallengerInitiative']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getChallengerInitiative(input);
  }
}
