/**
 * SourcingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SourcingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SourcingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SourcingRepository,
} from "@morphora/services/initiatives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SourcingRepositoryDdb } from "./sourcing-repository.ddb.js";

/**
 * SourcingRepositoryAdapter
 *
 * Implements SourcingRepository port for infrastructure layer.
 */
export class SourcingRepositoryAdapter implements SourcingRepository {
  private readonly ddb: SourcingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SourcingRepositoryDdb(this.dynamoClient);
  }

  async setInitiativeSourcing(input: Parameters<SourcingRepository['setInitiativeSourcing']>[0]): Promise<Awaited<ReturnType<SourcingRepository['setInitiativeSourcing']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setInitiativeSourcing(input);
  }
}
