/**
 * GetSignal DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetSensingSignalParams } from "@morphora/core/sensing";

export function createGetSignalRequest(overrides: Partial<GetSensingSignalParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
