/**
 * SummaryRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SummaryRepository Port
 *
 * DDD: Application port for summaryrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCadenceSummaryInput, GetCadenceSummaryOutput } from "../dto/summary.dto";
export interface SummaryRepository {
  getCadenceSummary(input: GetCadenceSummaryInput): Promise<GetCadenceSummaryOutput>;
}

export type { GetCadenceSummaryInput, GetCadenceSummaryOutput } from "../dto/summary.dto";
