/**
 * RemediateShadowITCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { remediateShadowITCase } from "@morphora/api-server/domains/cases/handlers";
import type { CasesDDDDependencies } from "@morphora/api-server/domains/cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@morphora/tests/shared";
import { CASES_USE_CASES } from "../__factories__/use-cases.js";

describe("RemediateShadowITCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CasesDDDDependencies>(
      CASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { caseId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRemediateShadowITCase, "execute").mockResolvedValue(useCaseResult);

    await remediateShadowITCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRemediateShadowITCase.execute).toHaveBeenCalledWith(expect.objectContaining({ caseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
