/**
 * Disposition DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disposition DTOs
 *
 * DDD: Application DTOs for Disposition use cases.
 */

import type { SetCoreSystemDispositionParams, SetCoreSystemDispositionRequestInput } from "@morphora/core/footprint/types";

export type SetCoreSystemDispositionInput = SetCoreSystemDispositionParams & SetCoreSystemDispositionRequestInput;

export type SetCoreSystemDispositionOutput = {};
