/**
 * SpeedTag DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SpeedTag DTOs
 *
 * DDD: Application DTOs for SpeedTag use cases.
 */

import type { SetCoreSystemSpeedTagParams, SetCoreSystemSpeedTagRequestInput } from "@morphora/core/footprint/types";

export type SetCoreSystemSpeedTagInput = SetCoreSystemSpeedTagParams & SetCoreSystemSpeedTagRequestInput;

export type SetCoreSystemSpeedTagOutput = {};
