/**
 * System DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * System DTOs
 *
 * DDD: Application DTOs for System use cases.
 */

import type { CreateCoreSystemRequestInput, GetCoreSystemParams } from "@morphora/core/footprint/types";

export type ListCoreSystemsInput = {};

export type CreateCoreSystemInput = CreateCoreSystemRequestInput;

export type GetCoreSystemInput = GetCoreSystemParams;

export type ListCoreSystemsOutput = {};

export type CreateCoreSystemOutput = {};

export type GetCoreSystemOutput = {};
