/**
 * Handlers for Disposition
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FootprintDomainModule } from "../dependencies/footprint-ddd.dependencies.js";
import type { SetCoreSystemDispositionInput } from "@morphora/services/footprint";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v0/tenants/me/footprint/systems/{systemId}/disposition
 * Operation: setCoreSystemDisposition
 */
export async function setCoreSystemDisposition(
  request: FastifyRequest<{ Params: { systemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FootprintDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const body = (request.body ?? {}) as Record<string, unknown>;
  const input = { ...body, systemId: request.params.systemId } as SetCoreSystemDispositionInput;
  const result = await deps.useCases.dispositions.update.execute(input);
  return reply.code(200).send(result);
}


