/**
 * ExecuteRecordDecision - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordDecision Use Case
 *
 * DDD: Application use case for get Decision.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordDecisionInput, RecordDecisionOutput } from "../dto/decision.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { DecisionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordDecision {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decision: DecisionRepository
  ) {}

  async execute(input: RecordDecisionInput): Promise<RecordDecisionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.decId();

    // All field names extracted from OpenAPI spec: decidedAt, decisionType, outcome, rationale, relatedEntityId, relatedEntityType, shapeshifterRole
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).decisionType) {
      throw new ValidationError("decisionType is required");
    }
    if (!(input as any).outcome) {
      throw new ValidationError("outcome is required");
    }
    if (!(input as any).rationale) {
      throw new ValidationError("rationale is required");
    }

    const entityId = this.idGenerator.decId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.decision.recordDecision({ ...input, id: entityId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${entityId}`);
    }

    return entity as RecordDecisionOutput;
  }
}
