/**
 * Repository interface for HypeAssessment
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  HypeAssessmentEntity
} from "../models/hype-assessment.entity.js";
import type {
  UpsertHypeAssessmentRequestInput
} from "../types/index.js";
/**
 * HypeAssessmentRepository Interface
 */
export interface HypeAssessmentRepository extends UpdateReadRepository<HypeAssessmentEntity, UpsertHypeAssessmentRequestInput, string, Record<string, never>> {

}
