/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Decisions Domain Use Cases
 * 
 * List of all use case names for the decisions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DECISIONS_USE_CASES = [
  "executeGetCadenceSummary",
  "executeGetDecision",
  "executeListDecisions",
  "executeRecordDecision"
] as const;
