/**
 * SignalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SignalRepository Port
 *
 * DDD: Application port for signalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateSensingSignalInput, CreateSensingSignalOutput, GetSensingSignalInput, GetSensingSignalOutput, ListSensingSignalsInput, ListSensingSignalsOutput } from "../dto/signal.dto";
export interface SignalRepository {
  listSensingSignals(input: ListSensingSignalsInput): Promise<ListSensingSignalsOutput>;
  createSensingSignal(input: CreateSensingSignalInput): Promise<CreateSensingSignalOutput>;
  getSensingSignal(input: GetSensingSignalInput): Promise<GetSensingSignalOutput>;
}

export type { CreateSensingSignalInput, CreateSensingSignalOutput, GetSensingSignalInput, GetSensingSignalOutput, ListSensingSignalsInput, ListSensingSignalsOutput } from "../dto/signal.dto";
