/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DecisionsDomainModule } from "../dependencies/decisions-ddd.dependencies.js";
import type { GetDecisionInput, ListDecisionsInput, RecordDecisionInput } from "@morphora/services/decisions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/decisions
 * Operation: listDecisions
 */
export async function listDecisions(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DecisionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDecisionsInput = {};
  const result = await deps.useCases.decisions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/decisions
 * Operation: recordDecision
 */
export async function recordDecision(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DecisionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = (request.body ?? {}) as RecordDecisionInput;
  const result = await deps.useCases.decisions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/decisions/{decisionId}
 * Operation: getDecision
 */
export async function getDecision(
  request: FastifyRequest<{ Params: { decisionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DecisionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDecisionInput = {
    decisionId: request.params.decisionId,
  };
  const result = await deps.useCases.decisions.get.execute(input);
  return reply.code(200).send(result);
}


