/**
 * InitiativeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InitiativeRepository Port
 *
 * DDD: Application port for initiativerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateChallengerInitiativeInput, CreateChallengerInitiativeOutput, GetChallengerInitiativeInput, GetChallengerInitiativeOutput, ListChallengerInitiativesInput, ListChallengerInitiativesOutput } from "../dto/initiative.dto";
export interface InitiativeRepository {
  listChallengerInitiatives(input: ListChallengerInitiativesInput): Promise<ListChallengerInitiativesOutput>;
  createChallengerInitiative(input: CreateChallengerInitiativeInput): Promise<CreateChallengerInitiativeOutput>;
  getChallengerInitiative(input: GetChallengerInitiativeInput): Promise<GetChallengerInitiativeOutput>;
}

export type { CreateChallengerInitiativeInput, CreateChallengerInitiativeOutput, GetChallengerInitiativeInput, GetChallengerInitiativeOutput, ListChallengerInitiativesInput, ListChallengerInitiativesOutput } from "../dto/initiative.dto";
