/**
 * Disposition Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DispositionEntity } from "@morphora/core/footprint/models/index.js";
import { footprintSchemas } from "@morphora/core/footprint";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ftp";

export function createDisposition(overrides: Partial<DispositionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    ...overrides,
  };

  return footprintSchemas.Disposition.parse(raw);
}

export function dispositionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDisposition(overrides));
}
