/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildCasesDomainModule } from "./cases/dependencies/cases-ddd.dependencies.js";
export { buildDecisionsDomainModule } from "./decisions/dependencies/decisions-ddd.dependencies.js";
export { buildFootprintDomainModule } from "./footprint/dependencies/footprint-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildInitiativesDomainModule } from "./initiatives/dependencies/initiatives-ddd.dependencies.js";
export { buildPacksDomainModule } from "./packs/dependencies/packs-ddd.dependencies.js";
export { buildPartnersDomainModule } from "./partners/dependencies/partners-ddd.dependencies.js";
export { buildSensingDomainModule } from "./sensing/dependencies/sensing-ddd.dependencies.js";
export { buildTalentDomainModule } from "./talent/dependencies/talent-ddd.dependencies.js";

// Export all domain dependency types
export type { CasesDomainModule } from "./cases/dependencies/cases-ddd.dependencies.js";
export type { DecisionsDomainModule } from "./decisions/dependencies/decisions-ddd.dependencies.js";
export type { FootprintDomainModule } from "./footprint/dependencies/footprint-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { InitiativesDomainModule } from "./initiatives/dependencies/initiatives-ddd.dependencies.js";
export type { PacksDomainModule } from "./packs/dependencies/packs-ddd.dependencies.js";
export type { PartnersDomainModule } from "./partners/dependencies/partners-ddd.dependencies.js";
export type { SensingDomainModule } from "./sensing/dependencies/sensing-ddd.dependencies.js";
export type { TalentDomainModule } from "./talent/dependencies/talent-ddd.dependencies.js";
