/**
 * ExecuteListSensingSignals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSensingSignals Use Case
 *
 * DDD: Application use case for list Signal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSensingSignalsInput, ListSensingSignalsOutput } from "../dto/signal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { SignalRepository } from "../ports";

export class ExecuteListSensingSignals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly signal: SignalRepository
  ) {}

  async execute(input: ListSensingSignalsInput): Promise<ListSensingSignalsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.snsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.signal.listSensingSignals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSensingSignalsOutput;
  }
}
