/**
 * ExecuteGetSensingSignal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSensingSignal Use Case
 *
 * DDD: Application use case for get Signal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSensingSignalInput, GetSensingSignalOutput } from "../dto/signal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { SignalRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSensingSignal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly signal: SignalRepository
  ) {}

  async execute(input: GetSensingSignalInput): Promise<GetSensingSignalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.snsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).signalId) {
      throw new ValidationError("signalId is required");
    }
    const signalId = (input as any).signalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.signal.getSensingSignal({ signalId: signalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${signalId}`);
    }

    return entity as GetSensingSignalOutput;
  }
}
