/**
 * ShadowItRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShadowItRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ShadowItRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ShadowItRepository,
} from "@morphora/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ShadowItRepositoryDdb } from "./shadow-it-repository.ddb.js";

/**
 * ShadowItRepositoryAdapter
 *
 * Implements ShadowItRepository port for infrastructure layer.
 */
export class ShadowItRepositoryAdapter implements ShadowItRepository {
  private readonly ddb: ShadowItRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ShadowItRepositoryDdb(this.dynamoClient);
  }

  async listShadowITCases(input: Parameters<ShadowItRepository['listShadowITCases']>[0]): Promise<Awaited<ReturnType<ShadowItRepository['listShadowITCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listShadowITCases(input);
  }

  async openShadowITCase(input: Parameters<ShadowItRepository['openShadowITCase']>[0]): Promise<Awaited<ReturnType<ShadowItRepository['openShadowITCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openShadowITCase(input);
  }

  async getShadowITCase(input: Parameters<ShadowItRepository['getShadowITCase']>[0]): Promise<Awaited<ReturnType<ShadowItRepository['getShadowITCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getShadowITCase(input);
  }
}
