/**
 * Routes for Summary
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCadenceSummary } from "../handlers/summary.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function summaryRoutes(fastify: FastifyInstance) {
  // GET /v0/tenants/me/cadence/summary (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/cadence/summary",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDecisionsDependenciesForRequest();
        await getCadenceSummary(request, reply, deps);
      });
    }
  );


}
