/**
 * HypeAssessmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HypeAssessmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HypeAssessmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HypeAssessmentRepository,
} from "@morphora/services/sensing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HypeAssessmentRepositoryDdb } from "./hype-assessment-repository.ddb.js";

/**
 * HypeAssessmentRepositoryAdapter
 *
 * Implements HypeAssessmentRepository port for infrastructure layer.
 */
export class HypeAssessmentRepositoryAdapter implements HypeAssessmentRepository {
  private readonly ddb: HypeAssessmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HypeAssessmentRepositoryDdb(this.dynamoClient);
  }

  async upsertHypeAssessment(input: Parameters<HypeAssessmentRepository['upsertHypeAssessment']>[0]): Promise<Awaited<ReturnType<HypeAssessmentRepository['upsertHypeAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertHypeAssessment(input);
  }
}
