/**
 * SignalRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SignalRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SignalRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SignalRepository,
} from "@morphora/services/sensing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SignalRepositoryDdb } from "./signal-repository.ddb.js";

/**
 * SignalRepositoryAdapter
 *
 * Implements SignalRepository port for infrastructure layer.
 */
export class SignalRepositoryAdapter implements SignalRepository {
  private readonly ddb: SignalRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SignalRepositoryDdb(this.dynamoClient);
  }

  async listSensingSignals(input: Parameters<SignalRepository['listSensingSignals']>[0]): Promise<Awaited<ReturnType<SignalRepository['listSensingSignals']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSensingSignals(input);
  }

  async createSensingSignal(input: Parameters<SignalRepository['createSensingSignal']>[0]): Promise<Awaited<ReturnType<SignalRepository['createSensingSignal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSensingSignal(input);
  }

  async getSensingSignal(input: Parameters<SignalRepository['getSensingSignal']>[0]): Promise<Awaited<ReturnType<SignalRepository['getSensingSignal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSensingSignal(input);
  }
}
