/**
 * GapRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GapRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GapRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GapRepository,
} from "@morphora/services/talent";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GapRepositoryDdb } from "./gap-repository.ddb.js";

/**
 * GapRepositoryAdapter
 *
 * Implements GapRepository port for infrastructure layer.
 */
export class GapRepositoryAdapter implements GapRepository {
  private readonly ddb: GapRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GapRepositoryDdb(this.dynamoClient);
  }

  async listTalentGaps(input: Parameters<GapRepository['listTalentGaps']>[0]): Promise<Awaited<ReturnType<GapRepository['listTalentGaps']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTalentGaps(input);
  }

  async createTalentGap(input: Parameters<GapRepository['createTalentGap']>[0]): Promise<Awaited<ReturnType<GapRepository['createTalentGap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createTalentGap(input);
  }

  async getTalentGap(input: Parameters<GapRepository['getTalentGap']>[0]): Promise<Awaited<ReturnType<GapRepository['getTalentGap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTalentGap(input);
  }

  async updateTalentGap(input: Parameters<GapRepository['updateTalentGap']>[0]): Promise<Awaited<ReturnType<GapRepository['updateTalentGap']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateTalentGap(input);
  }
}
