/**
 * Initiative DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Initiative DTOs
 *
 * DDD: Application DTOs for Initiative use cases.
 */

import type { CreateChallengerInitiativeRequestInput, GetChallengerInitiativeParams } from "@morphora/core/initiatives/types";

export type ListChallengerInitiativesInput = {};

export type CreateChallengerInitiativeInput = CreateChallengerInitiativeRequestInput;

export type GetChallengerInitiativeInput = GetChallengerInitiativeParams;

export type ListChallengerInitiativesOutput = {};

export type CreateChallengerInitiativeOutput = {};

export type GetChallengerInitiativeOutput = {};
