/**
 * Gap DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Gap DTOs
 *
 * DDD: Application DTOs for Gap use cases.
 */

import type { CreateTalentGapRequestInput, GetTalentGapParams, UpdateTalentGapParams, UpdateTalentGapRequestInput } from "@morphora/core/talent/types";

export type ListTalentGapsInput = {};

export type CreateTalentGapInput = CreateTalentGapRequestInput;

export type GetTalentGapInput = GetTalentGapParams;

export type UpdateTalentGapInput = UpdateTalentGapParams & UpdateTalentGapRequestInput;

export type ListTalentGapsOutput = {};

export type CreateTalentGapOutput = {};

export type GetTalentGapOutput = {};

export type UpdateTalentGapOutput = {};
