/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@morphora/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@morphora/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@morphora/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _cases from "./cases/index.js";
import * as _decisions from "./decisions/index.js";
import * as _footprint from "./footprint/index.js";
import * as _identity from "./identity/index.js";
import * as _initiatives from "./initiatives/index.js";
import * as _packs from "./packs/index.js";
import * as _partners from "./partners/index.js";
import * as _sensing from "./sensing/index.js";
import * as _talent from "./talent/index.js";

// Export as namespaces
export const cases = _cases;
export const decisions = _decisions;
export const footprint = _footprint;
export const identity = _identity;
export const initiatives = _initiatives;
export const packs = _packs;
export const partners = _partners;
export const sensing = _sensing;
export const talent = _talent;
