/**
 * Handlers for HypeAssessment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SensingDomainModule } from "../dependencies/sensing-ddd.dependencies.js";
import type { UpsertHypeAssessmentInput } from "@morphora/services/sensing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v0/tenants/me/sensing/signals/{signalId}/hype-assessment
 * Operation: upsertHypeAssessment
 */
export async function upsertHypeAssessment(
  request: FastifyRequest<{ Params: { signalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SensingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const body = (request.body ?? {}) as Record<string, unknown>;
  const input = { ...body, signalId: request.params.signalId } as UpsertHypeAssessmentInput;
  const result = await deps.useCases.hypeAssessments.get.execute(input);
  return reply.code(200).send(result);
}


