/**
 * ExecuteCreateCoreSystem - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateCoreSystem Use Case
 *
 * DDD: Application use case for create System.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateCoreSystemInput, CreateCoreSystemOutput } from "../dto/system.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { SystemRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateCoreSystem {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly system: SystemRepository
  ) {}

  async execute(input: CreateCoreSystemInput): Promise<CreateCoreSystemOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ftpId();

    // All field names extracted from OpenAPI spec: couplingWarning, name, runSpendShare, sloCompliance, speedTag
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.speedTag) {
      throw new ValidationError("speedTag is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (footprint domain)
    const entityId = this.idGenerator.ftpId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.system.createCoreSystem({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateCoreSystemOutput;
  }
}
