/**
 * PackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PackRepository Port
 *
 * DDD: Application port for packrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateExecPackInput, CreateExecPackOutput, GetExecPackInput, GetExecPackOutput, ListExecPacksInput, ListExecPacksOutput } from "../dto/pack.dto";
export interface PackRepository {
  listExecPacks(input: ListExecPacksInput): Promise<ListExecPacksOutput>;
  createExecPack(input: CreateExecPackInput): Promise<CreateExecPackOutput>;
  getExecPack(input: GetExecPackInput): Promise<GetExecPackOutput>;
}

export type { CreateExecPackInput, CreateExecPackOutput, GetExecPackInput, GetExecPackOutput, ListExecPacksInput, ListExecPacksOutput } from "../dto/pack.dto";
