/**
 * Routes for HypeAssessment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { upsertHypeAssessment } from "../handlers/hype-assessment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function hypeAssessmentRoutes(fastify: FastifyInstance) {
  // PUT /v0/tenants/me/sensing/signals/{signalId}/hype-assessment (unscoped; scope set for security middleware)
  fastify.put(
    "/v0/tenants/me/sensing/signals/:signalId/hype-assessment",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { signalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSensingDependenciesForRequest();
        await upsertHypeAssessment(request, reply, deps);
      });
    }
  );


}
