/**
 * Routes for Signal
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createSensingSignal, getSensingSignal, listSensingSignals } from "../handlers/signal.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function signalRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/sensing/signals (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/sensing/signals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSensingDependenciesForRequest();
        await createSensingSignal(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/sensing/signals (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/sensing/signals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSensingDependenciesForRequest();
        await listSensingSignals(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/sensing/signals/{signalId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/sensing/signals/:signalId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { signalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSensingDependenciesForRequest();
        await getSensingSignal(request, reply, deps);
      });
    }
  );


}
