/**
 * SpeedTag Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/footprint.openapi.types.js";
import { schemas } from "../schemas/footprint.schemas.js";

/**
 * Entity: SpeedTagEntity
 * Description: Represents the SpeedTag domain model.
 * Source: schemas.SpeedTag
 * Type: Domain Entity (API)
 */
export const SpeedTagEntitySchema = schemas.SpeedTag;
export type SpeedTagEntity = components["schemas"]["SpeedTag"];
