/**
 * Routes for Criticality
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { setPartnerCriticality } from "../handlers/criticality.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function criticalityRoutes(fastify: FastifyInstance) {
  // PUT /v0/tenants/me/partners/{partnerId}/criticality (unscoped; scope set for security middleware)
  fastify.put(
    "/v0/tenants/me/partners/:partnerId/criticality",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { partnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPartnersDependenciesForRequest();
        await setPartnerCriticality(request, reply, deps);
      });
    }
  );


}
