/**
 * ExecuteScaleInitiative - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteScaleInitiative Use Case
 *
 * DDD: Application use case for get Scale.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ScaleInitiativeInput, ScaleInitiativeOutput } from "../dto/scale.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { ScaleRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteScaleInitiative {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scale: ScaleRepository
  ) {}

  async execute(input: ScaleInitiativeInput): Promise<ScaleInitiativeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.iniId();

    // All field names extracted from OpenAPI spec: rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).initiativeId) {
      throw new ValidationError("initiativeId is required");
    }
    const initiativeId = (input as any).initiativeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.scale.scaleInitiative({ ...input, initiativeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${initiativeId}`);
    }

    return entity as ScaleInitiativeOutput;
  }
}
