/**
 * Routes for Initiative
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createChallengerInitiative, getChallengerInitiative, listChallengerInitiatives } from "../handlers/initiative.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function initiativeRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/initiatives (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/initiatives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInitiativesDependenciesForRequest();
        await createChallengerInitiative(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/initiatives (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/initiatives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInitiativesDependenciesForRequest();
        await listChallengerInitiatives(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/initiatives/{initiativeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/initiatives/:initiativeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInitiativesDependenciesForRequest();
        await getChallengerInitiative(request, reply, deps);
      });
    }
  );


}
