/**
 * Pack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pack DTOs
 *
 * DDD: Application DTOs for Pack use cases.
 */

import type { CreateExecPackRequestInput, GetExecPackParams } from "@morphora/core/packs/types";

export type ListExecPacksInput = {};

export type CreateExecPackInput = CreateExecPackRequestInput;

export type GetExecPackInput = GetExecPackParams;

export type ListExecPacksOutput = {};

export type CreateExecPackOutput = {};

export type GetExecPackOutput = {};
