/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Talent Domain Use Cases
 * 
 * List of all use case names for the talent domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TALENT_USE_CASES = [
  "executeCreateTalentGap",
  "executeGetTalentGap",
  "executeListTalentGaps",
  "executeUpdateTalentGap"
] as const;
