/**
 * Partner DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Partner DTOs
 *
 * DDD: Application DTOs for Partner use cases.
 */

import type { CreatePartnerRequestInput, GetPartnerParams } from "@morphora/core/partners/types";

export type ListPartnersInput = {};

export type CreatePartnerInput = CreatePartnerRequestInput;

export type GetPartnerInput = GetPartnerParams;

export type ListPartnersOutput = {};

export type CreatePartnerOutput = {};

export type GetPartnerOutput = {};
