/**
 * Routes for Remediate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { remediateShadowITCase } from "../handlers/remediate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function remediateRoutes(fastify: FastifyInstance) {
  // PUT /v0/tenants/me/cases/shadow-it/{caseId}/remediate (unscoped; scope set for security middleware)
  fastify.put(
    "/v0/tenants/me/cases/shadow-it/:caseId/remediate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await remediateShadowITCase(request, reply, deps);
      });
    }
  );


}
