/**
 * Handlers for Sourcing
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InitiativesDomainModule } from "../dependencies/initiatives-ddd.dependencies.js";
import type { SetInitiativeSourcingInput } from "@morphora/services/initiatives";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v0/tenants/me/initiatives/{initiativeId}/sourcing
 * Operation: setInitiativeSourcing
 */
export async function setInitiativeSourcing(
  request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InitiativesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const body = (request.body ?? {}) as Record<string, unknown>;
  const input = { ...body, initiativeId: request.params.initiativeId } as SetInitiativeSourcingInput;
  const result = await deps.useCases.sourcings.update.execute(input);
  return reply.code(200).send(result);
}


