/**
 * GetShadowITCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getShadowITCase } from "@morphora/api-server/domains/cases/handlers";
import type { CasesDDDDependencies } from "@morphora/api-server/domains/cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@morphora/tests/shared";
import { CASES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetShadowITCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CasesDDDDependencies>(
      CASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetShadowITCase, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { caseId: entity.id };

    await getShadowITCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetShadowITCase.execute).toHaveBeenCalledWith(expect.objectContaining({ caseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { caseId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetShadowITCase, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getShadowITCase(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
