/**
 * GetSystem DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: footprint
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCoreSystemParams } from "@morphora/core/footprint";

export function createGetSystemRequest(overrides: Partial<GetCoreSystemParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
