/**
 * ExecuteListExecPacks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListExecPacks Use Case
 *
 * DDD: Application use case for list Pack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListExecPacksInput, ListExecPacksOutput } from "../dto/pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { PackRepository } from "../ports";

export class ExecuteListExecPacks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pack: PackRepository
  ) {}

  async execute(input: ListExecPacksInput): Promise<ListExecPacksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pckId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.pack.listExecPacks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListExecPacksOutput;
  }
}
