/**
 * ExecutePublishExecPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishExecPack Use Case
 *
 * DDD: Application use case for get Publish.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishExecPackInput, PublishExecPackOutput } from "../dto/publish.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { PackRepository, PublishPublisher } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePublishExecPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly publish: PublishPublisher,
    private readonly pack: PackRepository
  ) {}

  async execute(input: PublishExecPackInput): Promise<PublishExecPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pckId();

    // All field names extracted from OpenAPI spec: challengerNote, concentrationNote, narrative, spendMixNote, stretchSqueezeNote
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).packId) {
      throw new ValidationError("packId is required");
    }
    const packId = (input as any).packId;

    // Publish via publisher port (pass correlation ID for response meta)
    const entity = await this.publish.publishExecPack({
      packId,
      orgId: this.context.getOrgId(),
      correlationId,
      ...(input as object),
    } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${packId}`);
    }

    return entity as PublishExecPackOutput;
  }
}
