/**
 * ExecuteGetExecPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetExecPack Use Case
 *
 * DDD: Application use case for get Pack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetExecPackInput, GetExecPackOutput } from "../dto/pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@morphora/services/_shared/index.js";
import type { PackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetExecPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pack: PackRepository
  ) {}

  async execute(input: GetExecPackInput): Promise<GetExecPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pckId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).packId) {
      throw new ValidationError("packId is required");
    }
    const packId = (input as any).packId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.pack.getExecPack({ packId: packId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${packId}`);
    }

    return entity as GetExecPackOutput;
  }
}
