/**
 * HypeAssessment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HypeAssessment DTOs
 *
 * DDD: Application DTOs for HypeAssessment use cases.
 */

import type { UpsertHypeAssessmentParams, UpsertHypeAssessmentRequestInput } from "@morphora/core/sensing/types";

export type UpsertHypeAssessmentInput = UpsertHypeAssessmentParams & UpsertHypeAssessmentRequestInput;

export type UpsertHypeAssessmentOutput = {};
