/**
 * Signal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sensing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Signal DTOs
 *
 * DDD: Application DTOs for Signal use cases.
 */

import type { CreateSensingSignalRequestInput, GetSensingSignalParams } from "@morphora/core/sensing/types";

export type ListSensingSignalsInput = {};

export type CreateSensingSignalInput = CreateSensingSignalRequestInput;

export type GetSensingSignalInput = GetSensingSignalParams;

export type ListSensingSignalsOutput = {};

export type CreateSensingSignalOutput = {};

export type GetSensingSignalOutput = {};
